### ISSUE TITLE
Code how social media will preview our page

### ISSUE THREAD

**Issue by rachaelbradley** [accessiblecommunity/accessiblecommunity.github.io#123]
We use the following social media:

- LInked In
- Instagram
- Facebook
- TikTok
- Mastadon

We need to add code to control how the pages show up when someone links to content on accessiblecommunity.org.

**Comment by alexisreytech** [comment]
This might be helpful to preview the website preview: [Meta Tags](https://metatags.io/).

**Comment by rachaelbradley** [comment]
Open Graph meta tags to get the data pertaining to the image, title, and description of your link.
https://ogp.me/
https://kinsta.com/blog/linkedin-debugger/
https://opengraph.dev/
