### ISSUE TITLE
Change primary-subtle border color for dark mode

### ISSUE THREAD

**Issue by alexisreytech** [accessiblecommunity/accessiblecommunity.github.io#129]
@brian-montgomery, for examples of this, a couple pages have this issue:

- The border around "1 in every 4" statistic on the homepage
- The border around "The 'a11y' in our..." on the services page
- The border around the summary portion of the tip of the week articles

**Comment by brian-montgomery** [comment]
@alexisreytech: Can you update the description with some more information on this?
