### ISSUE TITLE
Establish "Code of Conduct" Form

### ISSUE THREAD

**Issue by brian-montgomery** [accessiblecommunity/accessiblecommunity.github.io#173]
Create the "code of conduct" form to post to a Google Docs Spreadsheet, similar to the Volunteer Form.

*Note:* This form should not be directly shown to from the header or the site map.

**Comment by brian-montgomery** [comment]
@rachaelbradley: Can you take a screenshot or write up what fields need to be on this?

**Comment by brian-montgomery** [comment]
@alexisreytech: Sorry thatit's taken so long, here is a [zip file](https://github.com/accessiblecommunity/accessiblecommunity.github.io/files/14315768/team-info.zip) containing the Team Information Page. It includes the following:
* Full Name
* Cited Name (How you want credit to appear)
* LinkedIn Profile
* Mastodon Handle
* Twitter/X Handle
* Instragram Profile
* Checkbox to agree to the Code of Conduct
* T-shirt size (Optional, if they want one)
* Checkbox for whether to be a part of a Team Spotlight

**Comment by rachaelbradley** [comment]
There are two conditional portoins of the form. The first is the T-Shirt.
It asks if they want a Tshirt and if they do, it asks for tshirt size and
mailing address.

The second is the team spotlight. If yes it asks:
Background - Tell us a few sentences about your background and what
inspired you to join Accessible Community.
What is a fun fact about you that you can share with the world?
Image for social media - "There are valid security concerns with sharing
your photo online. You are welcome to provide a photo if thatis what you
prefer but you may also provide a bitmoji or image that brings you joy.
Feel free to provide several options.  Link to instructions for creating
bitmoji

**Comment by rachaelbradley** [comment]
The t-shirt also includes a link to the t-shirt sizing:

Links for form:

https://docs.google.com/document/d/1qN_AaJaMcjeyxg6zK63OJxsZbv-zwbONtFgZbiiISso


https://docs.google.com/spreadsheets/d/1tlTeDW1qNVGoIBlO3XuNFuf_x4twcZJr_4SlxKWSbHE/edit#gid=0
