### ISSUE TITLE
Fix headings and navigation in Footer

### ISSUE THREAD

**Issue by rachaelbradley** [accessiblecommunity/accessiblecommunity.github.io#269]
Right now there is a navigation region in the footer around the policy content but no headings.  Until we have a full sitemap in the footer, I suggest the following:

- Remove the navigation regions from the footer
- Add a Contact Us or Contact Information Heading (H2) above the Mailing Address, Email and Phone Number and de-emphasize the words Mailing Address, Email and Phone number
- Make User Policies, Staff Policies, and Find Us on Social Media H2 tags with the same styling as the Contact Us/Contact Information heading

**Comment by rachaelbradley** [comment]
Ellen reviewed and concurs. If possible, can this be completed by Wednesday?

**Comment by alexisreytech** [comment]
@brian-montgomery, I can make these changes if you want.
