### ISSUE TITLE
Make Header Size Consistent for Desktop/Mobile

### ISSUE THREAD

**Issue by alexisreytech** [accessiblecommunity/accessiblecommunity.github.io#46]
Try to reduce size of header on mobile screens by keeping hamburger menu icon on the right side.

**Comment by brian-montgomery** [comment]
@alexisreytech: I think #40 fixed this... at least, it does for me. Can you check?

**Comment by alexisreytech** [comment]
@brian-montgomery, looks good aside from breadcrumbs on mobile pushing hamburger menu sometimes to a new line, changing the header on mobile still.

**Comment by brian-montgomery** [comment]
Fixed in #120.
