### ISSUE TITLE
Try to Get Tool Names to be Announced as One Word for Screen Readers

### ISSUE THREAD

**Issue by alexisreytech** [accessiblecommunity/accessiblecommunity.github.io#85]
See if it is possible to have tool names announced as one word, so it sounds like "tally" for instance.

**Comment by rachaelbradley** [comment]
I am not sure this solution is correct as it will likely cause screen reader users more difficulty finding the tools. I think we need a discussion around tool naming with the UX group to evaluate what option is best:

- ta11y.org
- tally spelled ta11y
- total accessibility spelled ta11y
etc.

**Comment by brian-montgomery** [comment]
Fixed with #267
